# Generated by Django 4.2.15 on 2024-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='phtoto',
            field=models.ImageField(default=False, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
